#!/bin/bash -

node_name=$1

# remove waveform address for interface to reassign to batman interface
ip addr flush dev ${waveform_interface}

batctl meshif ${batman_interface} interface add ${waveform_interface}

%if batman_orig_interval:
batctl meshif ${batman_interface} orig_interval ${batman_orig_interval}
%endif

ifconfig ${batman_interface} ${radio_ip_addr}

if [ -f batman-routes ]
then
    ./batman-routes $node_name
fi
